#!/usr/bin/env bash
# Generate the .env files needed to run Comp locally in dev mode against the
# containers from packages/db/docker-compose.yml (Postgres) and
# docker-compose.local.yml (MinIO).
#
# Random secrets are generated once and shared across the apps that must agree
# on them. Third-party keys are left as FILL_ME placeholders for you to paste in.
# Existing .env files are never overwritten; delete one to regenerate it.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

gen() { openssl rand -base64 32 | tr -d '\n'; }

DATABASE_URL="postgresql://postgres:postgres@127.0.0.1:5432/comp"
SECRET_KEY="$(gen)"           # better-auth secret (api) and encryption secret (app)
ENCRYPTION_KEY="$(gen)"       # credential vault / integration secrets
REVALIDATION_SECRET="$(gen)"
INTERNAL_API_TOKEN="$(gen)"
SERVICE_TOKEN_TRIGGER="$(gen)"
SERVICE_TOKEN_PORTAL="$(gen)"

APP_URL="http://localhost:3000"
PORTAL_URL="http://localhost:3002"
API_URL="http://localhost:3333"

S3_ENDPOINT="http://localhost:9000"
S3_KEY="minioadmin"
S3_SECRET="minioadmin"
S3_REGION="us-east-1"

write() {
  local target="$1"
  if [[ -e "$target" ]]; then
    echo "skip   $target (exists)"
    cat >/dev/null
    return
  fi
  cat >"$target"
  chmod 600 "$target"
  echo "wrote  $target"
}

write "$ROOT/packages/db/.env" <<EOF
DATABASE_URL="$DATABASE_URL"
EOF

write "$ROOT/apps/framework-editor/.env" <<EOF
DATABASE_URL="$DATABASE_URL"
NEXT_PUBLIC_API_URL=$API_URL
BACKEND_API_URL=$API_URL
EOF

write "$ROOT/apps/api/.env" <<EOF
# --- Core ---
NODE_ENV=development
PORT=3333
BASE_URL=$API_URL
BETTER_AUTH_URL=$API_URL
NEXT_PUBLIC_APP_URL=$APP_URL
APP_URL=$APP_URL
PORTAL_URL=$PORTAL_URL
DATABASE_URL="$DATABASE_URL"
SELF_HOSTED=true
NEXT_PUBLIC_SELF_HOSTED=true

# --- Secrets (shared with app/portal; generated by scripts/local-env-init.sh) ---
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
INTERNAL_API_TOKEN=$INTERNAL_API_TOKEN
SERVICE_TOKEN_TRIGGER=$SERVICE_TOKEN_TRIGGER
SERVICE_TOKEN_PORTAL=$SERVICE_TOKEN_PORTAL

# --- Sign-in providers (create at console.cloud.google.com/apis/credentials) ---
AUTH_GOOGLE_ID=FILL_ME
AUTH_GOOGLE_SECRET=FILL_ME

# --- Email (resend.com) ---
RESEND_API_KEY=FILL_ME
RESEND_FROM_SYSTEM=Comp <noreply@FILL_ME_DOMAIN>
RESEND_FROM_DEFAULT=Comp <hello@FILL_ME_DOMAIN>

# --- Background jobs (cloud.trigger.dev -> project -> API keys -> dev key) ---
TRIGGER_SECRET_KEY=FILL_ME

# --- AI ---
OPENAI_API_KEY=FILL_ME
ANTHROPIC_API_KEY=FILL_ME

# --- Object storage (MinIO from docker-compose.local.yml) ---
APP_AWS_ENDPOINT=$S3_ENDPOINT
APP_AWS_REGION=$S3_REGION
APP_AWS_ACCESS_KEY_ID=$S3_KEY
APP_AWS_SECRET_ACCESS_KEY=$S3_SECRET
APP_AWS_BUCKET_NAME=comp-attachments
APP_AWS_ORG_ASSETS_BUCKET=comp-org-assets
APP_AWS_QUESTIONNAIRE_UPLOAD_BUCKET=comp-questionnaire-uploads
APP_AWS_KNOWLEDGE_BASE_BUCKET=comp-knowledge-base

# --- Optional / unused locally ---
MACED_API_KEY=mc_dev_dummy_api_key
EOF

write "$ROOT/apps/app/.env" <<EOF
# --- Core ---
NODE_ENV=development
DATABASE_URL="$DATABASE_URL"
BETTER_AUTH_URL=$API_URL
NEXT_PUBLIC_BETTER_AUTH_URL=$API_URL
NEXT_PUBLIC_API_URL=$API_URL
BACKEND_API_URL=$API_URL
NEXT_PUBLIC_PORTAL_URL=$PORTAL_URL
NEXT_PUBLIC_SELF_HOSTED=true
NEXT_OUTPUT_STANDALONE=false

# --- Secrets (shared with api; generated by scripts/local-env-init.sh) ---
AUTH_SECRET=$SECRET_KEY
SECRET_KEY=$SECRET_KEY
ENCRYPTION_KEY=$ENCRYPTION_KEY
REVALIDATION_SECRET=$REVALIDATION_SECRET
INTERNAL_API_TOKEN=$INTERNAL_API_TOKEN
SERVICE_TOKEN_TRIGGER=$SERVICE_TOKEN_TRIGGER

# --- Sign-in providers ---
AUTH_GOOGLE_ID=FILL_ME
AUTH_GOOGLE_SECRET=FILL_ME

# --- Email ---
RESEND_API_KEY=FILL_ME

# --- Background jobs (same Trigger.dev project as api) ---
TRIGGER_SECRET_KEY=FILL_ME

# --- AI ---
OPENAI_API_KEY=FILL_ME
ANTHROPIC_API_KEY=FILL_ME

# --- Object storage (MinIO) ---
APP_AWS_ENDPOINT=$S3_ENDPOINT
APP_AWS_REGION=$S3_REGION
APP_AWS_ACCESS_KEY_ID=$S3_KEY
APP_AWS_SECRET_ACCESS_KEY=$S3_SECRET
APP_AWS_BUCKET_NAME=comp-attachments
APP_AWS_ORG_ASSETS_BUCKET=comp-org-assets
APP_AWS_QUESTIONNAIRE_UPLOAD_BUCKET=comp-questionnaire-uploads
APP_AWS_KNOWLEDGE_BASE_BUCKET=comp-knowledge-base

# --- Analytics (disabled locally) ---
NEXT_PUBLIC_POSTHOG_HOST=/ingest
NEXT_PUBLIC_POSTHOG_KEY=
EOF

write "$ROOT/apps/portal/.env" <<EOF
# --- Core ---
NODE_ENV=development
DATABASE_URL="$DATABASE_URL"
BETTER_AUTH_URL=$API_URL
NEXT_PUBLIC_BETTER_AUTH_URL=$API_URL
NEXT_PUBLIC_API_URL=$API_URL

# --- Secrets (shared with api) ---
BETTER_AUTH_SECRET=$SECRET_KEY
INTERNAL_API_TOKEN=$INTERNAL_API_TOKEN

# --- Email ---
RESEND_API_KEY=FILL_ME
RESEND_DOMAIN=FILL_ME_DOMAIN

# --- Object storage (MinIO) ---
APP_AWS_ENDPOINT=$S3_ENDPOINT
APP_AWS_REGION=$S3_REGION
APP_AWS_ACCESS_KEY_ID=$S3_KEY
APP_AWS_SECRET_ACCESS_KEY=$S3_SECRET
APP_AWS_BUCKET_NAME=comp-attachments
EOF

echo
echo "Done. Search for FILL_ME in the generated files and paste in your keys."
